// Single source of truth for the closet-item classification taxonomy.
// Mirrored in mobile/src/taxonomy.ts for client-side display/filtering —
// keep the two in sync if you change values here.

export const GARMENT_TYPES = [
  "top",
  "bottom",
  "dress",
  "outerwear",
  "footwear",
  "accessory",
] as const;

export const TAXONOMY = {
  sleeveLength: [
    "long-sleeved",
    "short-sleeved",
    "sleeveless",
    "3/4 sleeve",
    "cap sleeve",
    "cropped",
    "full-length",
    "midi",
    "maxi",
    "mini",
  ],
  season: [
    "summer",
    "winter",
    "spring/fall",
    "all-season",
    "transitional",
    "tropical",
    "thermal",
  ],
  fabric: [
    "wool",
    "cotton",
    "linen",
    "silk",
    "cashmere",
    "denim",
    "leather",
    "suede",
    "corduroy",
    "flannel",
    "fleece",
    "polyester",
    "nylon",
    "spandex/elastane",
    "tweed",
    "velvet",
    "satin",
    "jersey",
    "canvas",
  ],
  weight: ["lightweight", "midweight", "heavyweight", "sheer", "thick", "thin"],
  fit: [
    "slim fit",
    "regular fit",
    "relaxed fit",
    "oversized",
    "tailored",
    "fitted",
    "boxy",
    "athletic fit",
    "skinny",
    "straight",
    "wide-leg",
    "tapered",
  ],
  formality: [
    "casual",
    "business casual",
    "formal",
    "semi-formal",
    "athleisure",
    "loungewear",
    "streetwear",
  ],
  pattern: [
    "solid",
    "striped",
    "plaid",
    "checkered",
    "floral",
    "polka dot",
    "houndstooth",
    "herringbone",
    "camo",
    "paisley",
    "animal print",
  ],
  texture: [
    "ribbed",
    "knit",
    "woven",
    "quilted",
    "brushed",
    "waffle-knit",
    "cable-knit",
    "terry",
  ],
  construction: [
    "structured",
    "unstructured",
    "layered",
    "cropped",
    "high-waisted",
    "low-rise",
    "double-breasted",
    "single-breasted",
    "single vent",
    "double vent",
  ],
  occasion: [
    "workwear",
    "activewear",
    "sleepwear",
    "swimwear",
    "outerwear",
    "formalwear",
  ],
  colorTreatment: [
    "solid",
    "heathered",
    "ombre",
    "tie-dye",
    "washed",
    "distressed",
    "faded",
  ],
} as const;

export type TaxonomyDimension = keyof typeof TAXONOMY;

export const TAXONOMY_DIMENSIONS = Object.keys(TAXONOMY) as TaxonomyDimension[];
